derror: Define type & related ones & impl Error/Format
* Define types which are required for defining the internal error type.
* Define the internal error type which satisfies the standard error
interface.
* Implement the Format method for satisfying the fmt.Formatter interface
and its test.
* Implement the Error method and its test.